# Generated by Django 4.2.7 on 2025-10-11 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="اسم الشهادة")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COMMERCIAL_REGISTER", "السجل التجاري"),
                            ("CLASSIFICATION", "شهادة التصنيف"),
                            ("ISO", "شهادة الأيزو"),
                            ("CAREER_LICENSE", "ترخيص مهني"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="نوع الشهادة",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(max_length=100, verbose_name="رقم الشهادة"),
                ),
                (
                    "issuing_authority",
                    models.CharField(max_length=200, verbose_name="الجهة المصدرة"),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="certificates/", verbose_name="الملف"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "شهادة الشركة",
                "verbose_name_plural": "شهادات الشركة",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="CostingCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SCREENING", "غربلة"),
                            ("CRUSHING", "كسارة"),
                            ("HAULING", "نقل"),
                            ("FEEDING", "تغذية"),
                            ("WASHING", "غسيل"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "مركز التكلفة",
                "verbose_name_plural": "مراكز التكلفة",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="اسم المعدة")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DT", "شاحنة قلاب"),
                            ("PC", "حفارة"),
                            ("WL", "محمل"),
                            ("GR", "جريدر"),
                            ("RL", "رولر"),
                            ("PLANT", "معدات المصنع"),
                        ],
                        max_length=10,
                        verbose_name="نوع المعدة",
                    ),
                ),
                ("model", models.CharField(max_length=200, verbose_name="الموديل")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الرقم التسلسلي"
                    ),
                ),
                (
                    "hours_operated",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ساعات التشغيل",
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الصيانة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "معدة",
                "verbose_name_plural": "المعدات",
            },
        ),
        migrations.CreateModel(
            name="FinancialStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="اسم القائمة")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BALANCE_SHEET", "الميزانية العمومية"),
                            ("INCOME_STATEMENT", "قائمة الدخل"),
                            ("CASH_FLOW", "قائمة التدفق النقدي"),
                            ("BUDGET", "الميزانية"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع القائمة",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="بداية الفترة")),
                ("period_end", models.DateField(verbose_name="نهاية الفترة")),
                (
                    "file",
                    models.FileField(
                        upload_to="financial_statements/", verbose_name="الملف"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "قائمة مالية",
                "verbose_name_plural": "القوائم المالية",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="InsurancePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="اسم البوليصة")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EQUIPMENT", "تأمين المعدات"),
                            ("EMPLOYEE", "تأمين الموظفين"),
                            ("LIABILITY", "تأمين المسؤولية"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع التأمين",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم البوليصة"
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(max_length=200, verbose_name="شركة التأمين"),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ التغطية",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="insurance/", verbose_name="الملف"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "بوليصة تأمين",
                "verbose_name_plural": "بوائص التأمين",
                "ordering": ["end_date"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم الفاتورة"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SCREENING", "غربلة"),
                            ("CRUSHING", "كسارة"),
                            ("HAULING", "نقل"),
                            ("FEEDING", "تغذية"),
                            ("WASHING", "غسيل"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع النشاط",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="اسم العميل"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="المبلغ",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="سعر الوحدة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "معلقة"),
                            ("PAID", "مدفوعة"),
                            ("CANCELLED", "ملغاة"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "فاتورة",
                "verbose_name_plural": "الفواتير",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="اسم الترخيص")),
                (
                    "license_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم الترخيص"
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(max_length=200, verbose_name="الجهة المصدرة"),
                ),
                ("issue_date", models.DateField(verbose_name="تاريخ الإصدار")),
                ("expiry_date", models.DateField(verbose_name="تاريخ الانتهاء")),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="licenses/", verbose_name="الملف"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "ترخيص",
                "verbose_name_plural": "التراخيص",
                "ordering": ["expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="MOU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المذكرة"),
                ),
                (
                    "party_name",
                    models.CharField(max_length=200, verbose_name="اسم الطرف الآخر"),
                ),
                (
                    "mou_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="رقم المذكرة"
                    ),
                ),
                ("signing_date", models.DateField(verbose_name="تاريخ التوقيع")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="القيمة",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="mous/", verbose_name="الملف"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "مذكرة تفاهم",
                "verbose_name_plural": "مذكرات التفاهم",
                "ordering": ["-signing_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("SCREENING", "غربلة"),
                            ("CRUSHING", "كسارة"),
                            ("HAULING", "نقل"),
                            ("FEEDING", "تغذية"),
                            ("WASHING", "غسيل"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع النشاط",
                    ),
                ),
                (
                    "actual_qty",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية الفعلية",
                    ),
                ),
                (
                    "contract_qty",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الكمية المتعاقد عليها",
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(editable=False, verbose_name="معدل الإنجاز"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True,
                        to="core.equipment",
                        verbose_name="المعدات المستخدمة",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل إنتاج",
                "verbose_name_plural": "سجلات الإنتاج",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FUEL", "وقود"),
                            ("MAINTENANCE", "صيانة"),
                            ("LABOR", "عمالة"),
                            ("MATERIALS", "مواد"),
                            ("OTHER", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="التصنيف",
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="التصنيف الفرعي"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="المبلغ",
                    ),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم الإيصال"
                    ),
                ),
                (
                    "costing_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.costingcenter",
                        verbose_name="مركز التكلفة",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.equipment",
                        verbose_name="المعدة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصروف",
                "verbose_name_plural": "المصروفات",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_name",
                    models.CharField(max_length=200, verbose_name="اسم الموظف"),
                ),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "check_in",
                    models.TimeField(blank=True, null=True, verbose_name="وقت الحضور"),
                ),
                (
                    "check_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="وقت الانصراف"
                    ),
                ),
                (
                    "hours_worked",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ساعات العمل",
                    ),
                ),
                (
                    "overtime_hours",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الساعات الإضافية",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "حضور",
                "verbose_name_plural": "سجلات الحضور",
                "ordering": ["-date"],
                "unique_together": {("employee_name", "date")},
            },
        ),
    ]
